version: '2'
services:
  web:
    image: msridharauc005
    build: .
    container_name: uc005
    restart: always
#    volumes:
#      - /home/ubuntu/webimage/images:/var/www/html
#      - /home/ubuntu/webimage/index.html:/var/www/html/index.html
    ports:
      - "81:80"
